spring:
  jpa:
    properties.hibernate.format-sql: true
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    show-sql: true
  sql:
    init:
      mode: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/telemetry_analyzer
    #url: jdbc:h2:file:./db/analyzer
    username: analyzer
    password: analyzer
kafka.constants:
  url: "localhost:9092"
  hub.topic: "telemetry.hubs.v1"
  snapshot.topic: "telemetry.snapshots.v1"
grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
logging.level.ru.gofc.smart_home: "DEBUG"